export const myProfileMisc = {
  username: "Алексей",
  name: "lexa2002",
  usage_goal: "Поиск соседа",
  desired_length: "1-2 года",
  chronotype: "Сова",
  max_budget: 25000,
  occupation: "Студент",
  smoking_status: "Не курю",
  gender: "Мужской",
  pets: "Аллергия",
  religion: "Атеизм",
  about:
    "Учусь в магистратуре ИТМО, ищу спокойного соседа, осуждаю беспорядок.",
  ready_for_smalltalk: false,
  id: "24eab778-70e9-4265-a33f-846aef78763f",
  status: "Ищущий",
  age: 21,
  city_name: "Санкт-Петербург",
  hometown_name: "Курск",
  hashtags_list: ["кино", "музыка", "игры", "IT", "архитектура", "пиво"],
  url: null,
  onboarding_completed: null,
  full_registration_completed: null,
  avatar_url: "/imgs/profile-photos/slider1.jpg",
};
